import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/ui/sonner";
import type { Metadata } from "next";
import React from "react";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
