import type { Metadata } from "next";
import { Geist } from "next/font/google";

import "../styles/globals.css";

import { Toaster } from "~/components/ui/sonner";
import { ReactQueryProvider } from "~/provider/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={`${geistSans.variable}`}>
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <div vaul-drawer-wrapper="">{children}</div>
          <Toaster closeButton richColors />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
